### ISSUE TITLE
Additional discussion for scipy.stats roadmap

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#10577]
Continuation of discussion from #10534. Several suggestions from @rlucas7 there:

- [ ] [Quantile fits](https://blogs.sas.com/content/iml/2018/03/07/fit-distribution-matching-quantile.html)
- [ ] post-hoc "tests", including Bayesian methods (e.g. https://arxiv.org/pdf/1506.06101.pdf)
- [ ] meta-analysis along the lines of `scipy.stats.combine_pvalues`
- [ ] more options for censoring / truncation
- [x] bootstrapping (see gh-13371)
- [ ] non-parametric versions of hypothesis tests (e.g. several in Hollander and Wolf)
- [ ] intervals beyond confidence intervals (prediction intervals, tolerance intervals, HPD (Bayesian))
- [x] `fit` methods for `rv_discrete` classes - (see gh-15436)
- [ ] (@chrisb83) exact calculation of `p`-values, where possible (see gh-13899), (@mdhaber) especially for ties
- [ ] (@mdhaber) distribution-specific documentation of each distribution method (see gh-10328)
- [ ] (@mdhaber) overhaul of distribution test suite (e.g. tests of every method with array input) 
- [ ] (@mdhaber) unify stats and mstats with consistent support for `axis`, `nan_policy`, and masked arrays (see gh-14651)
- [ ] (@mdhaber) overhaul of `rv_generic` and subclasses

**Comment by chrisb83** [comment]
For item 9, the current detailed roadmap states: 

> Improve statistical tests (p-value calculation, alternative hypothesis), for example implement an exact two-sided KS test (see gh-8341) or a one-sided Wilcoxon test (see gh-9046).

gh-9046 is already closed, so one should remove that example and rather link #4882. #10321 is a feature request for the exact Wilcoxon p-value, one could reference it as another example.

so overall, item 9 is covered, only slightly outdated

**Comment by rlucas7** [comment]
In #10534 I said item 8 `fit` for `rv_discrete` is the most glaring issue, still think so. 

*Short term* I'd propose: a `fit` method added into `rv_discrete`, then long term things could be migrated to `rv_generic` on a refactor. For the `rv_discrete` `fit` method aim would be to implement as similar functionality as possible to `rv_continuous` to make a refactor into `rv_generic` possible and hopefully easier. 

*Long term* I'm not sure, there are several related methods issues here:

1. `fit` code is in `rv_continuous`
2. `fit` has a `_fit_start` method and the likelihood and penalized likelihood methods (also in `rv_continuous`)
3. `fit` according to docstring has an MLE fitting procedure but in practice there are other fitting methods (e.g. item 1: quantile fits, moment method(s), non-parametric fit methods (e.g. Kaplan-Meier), [invariant estimators](https://en.wikipedia.org/wiki/Invariant_estimator#Pitman_estimator) etc.) if we plan to support both `MLE` and other estimation methods as well, perhaps the `fit` method should have it's own list of arguments similar to how the `minimize` function in `optimize` works? If we migrate things into `rv_generic` then the default can always be throwing a not implemented error if the MRO gets to the implementation in `rv_generic`. 

There are probably others I'm not thinking about that are as or more important. 

I'm not sure if that is the best way, or what techniques are in scope and out of scopy for long term but wanted to point out the issues and see what long term approach should look like and how it matches with short term.

**Comment by rlucas7** [comment]
Implementing `fit` in the discrete distributions would remove some of this section in the docs:

https://docs.scipy.org/doc/scipy/reference/tutorial/stats.html#discrete-points-label

Thinking about the class structure some more, I'd guess the class structure would not support a mixed distribution (e.g. Tweedie) which is a point mass at 0 and an (absolutely) continuous distribution on the positive half-line.

**Comment by derrynknife** [comment]
For item 4:

Any news on the progress of censoring and truncation? Do we have a format in which the data should be passed to the `fit` method?

**Comment by rlucas7** [comment]
> For item 4:
> 
> Any news on the progress of censoring and truncation? Do we have a format in which the data should be passed to the `fit` method?

AFAICS no progress on the item, we've thought about it some but no pull requests yet

**Comment by mdhaber** [comment]
There are rumors that @WarrenWeckesser has code : )

**Comment by WarrenWeckesser** [comment]
If the reference to "censoring" means fitting a probability distribution to censored data, then yes, I have work in progress that should show up in a PR "soon".  I realize that the Weckesser distribution of "soon" is fat-tailed, so let's say before Christmas. :)

**Comment by mdhaber** [comment]
Does anyone know the history of `mstats`? As gh-5474 notes, there is a lot of duplicate code between the two, yet as changes are made in one or the other, there have been attempts to keep them aligned (gh-5474, gh-2296) without unifying them. Is that desirable? Do we plan to keep maintaining two separate stats packages? It seems like there is still interest from users for using masked arrays for statistics (e.g. gh-12898 asks for `binned_statistic_dd` to support masked arrays), but do we have a vision for what we'd like to see? If we want to see the two unified, it might make sense to add it as a roadmap item.
