### ISSUE TITLE
MAINT: ppc64le support tracking issue

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#10965]
Tracking issue for achieving full test suite support for `ppc64le` architecture following merge of the POWER8 Travis CI test job in #9684, along with some failing tests decorated with `xfails`. I'll make a small checklist & perhaps experts in the appropriate subpackages can chip away at it over time. 

Remember that some of these failures may be observed on the CI pp64le node but not on the gcc compile farm machine of equivalent architecture (but different OS/Python, etc.) & vice-versa.

- [ ] `scipy/linalg/tests/test_decomp.py` : `test_aligned_mem()`
- [ ] `scipy/optimize/tests/test__differential_evolution.py`  : `test_L8()`
- [ ] `scipy/sparse/linalg/eigen/lobpcg/tests/test_lobpcg.py` : `test_tolerance_float32()`
- [ ] `scipy/sparse/linalg/isolve/tests/test_iterative.py` :  `test_maxiter_worsening()`
- [ ] `scipy/sparse/tests/test_base.py` : `TestLIL : test_dot()`
- [ ] `scipy/special/tests/test_basic.py` :  `test_jv_cephes_vs_amos()` & `test_yv_cephes_vs_amos`
- [ ] `scipy/special/tests/test_data.py` : `BOOST_TESTS ` parameters
- [ ] `scipy/special/tests/test_orthogonal.py` : `test_roots_genlaguerre()`
- [ ] `scipy/stats/tests/test_mstats_basic.py` : `test_kendalltau()`

**Comment by tylerjereddy** [comment]
`test_kendalltau()` can crash & circumvent the `xfail`, so now proposing a `skipif` for that test in #10975

**Comment by isuruf** [comment]
`linalg/tests/test_solvers.py::test_solve_discrete_are` fails with

```
>       assert_array_almost_equal(res, np.zeros_like(res), decimal=dec)

E       AssertionError: 

E       Arrays are not almost equal to 15 decimals

E       

E       Mismatch: 25%

E       Max absolute difference: 1.88737914e-15

E       Max relative difference: inf

E        x: array([[2.220446049250313e-16, 4.440892098500626e-16],

E              [4.440892098500626e-16, 1.887379141862766e-15]])

E        y: array([[0., 0.],

E              [0., 0.]])
```

**Comment by rgommers** [comment]
> `linalg/tests/test_solvers.py::test_solve_discrete_are` fails with

with OpenBLAS? it passes in our test suite, so likely an OpenBLAS issue

**Comment by isuruf** [comment]
With Reference LAPACK

**Comment by ev-br** [comment]
Can probably change the test to use assert_allclose(..., atol=1e-15)

**Comment by ev-br** [comment]
Can probably change the test to use assert_allclose(..., atol=1e-15)

**Comment by isuruf** [comment]
https://github.com/scipy/scipy/pull/11046

**Comment by tylerjereddy** [comment]
I'm seeing more problems in `ppc64le` CI again lately, unrelated to the changes in the PRs in question, for example:

https://travis-ci.org/scipy/scipy/builds/609946789?utm_medium=notification&utm_source=github_status

https://travis-ci.org/scipy/scipy/builds/610253991?utm_source=github_status&utm_medium=notification

**Comment by rgommers** [comment]
Indeed, TravisCI support still seems shaky
