### ISSUE TITLE
FromTravis migration tracker

### ISSUE THREAD

**Issue by ilayn** [scipy/scipy#13134]
Since many people are working on different parts of this I think we better take out the actual work out of the discussions scattered around. 

Currently Travis matrix is as follows

 - [ ] ARM - Test Group 1
 - [ ] ARM - Test Group 2
 - [x] Pre-release Dependencies, Source Dist (**-> In Azure now**)
 - [x] Coverage, Full test suite (**--> In Azure now**)
 - [x] Python 3.7 Debug (**--> In GitHub Actions** #13136 )
 - [ ] Python 3.7 PowerPc
 - [x] Pre-release Deps, 64-bit BLAS (**--> In Azure now**)
 - [x] Refguide-check, Latest NumPy (**--> In Azure now**)
 - [x] Source Distribution (**--> In Azure now**)
 - [x] Wheel, Optimised, GCC 4.8 (**--> In Azure now**)

Could you please edit, cross and put where the new location is so we don't get conflicts? 

Pinging @tylerjereddy @mattip for heads up

**Comment by tylerjereddy** [comment]
I think @peterbell10 wants to refactor to a template-based approach or something like that. I'm all for reducing duplication, but do note that it does of course make it slightly harder to split the effort over many volunteers if what is already there is going to be changed soon.

I don't think the pre-release deps PR was merged yet--Ralf and Peter have comments there

**Comment by ilayn** [comment]
Should we add the remaining three to GitHub too maybe to balance it a bit better?

**Comment by peterbell10** [comment]
Do any of the other CI platforms actually offer arm64 or powerpc workers?

**Comment by rgommers** [comment]
> Do any of the other CI platforms actually offer arm64 or powerpc workers?

Drone and Shippable have ARM64, but those aren't powerful enough - we should keep this on TravisCI. 

No other CI platforms have ppc64le. We keep it too. I think we're all done here.

**Comment by andyfaff** [comment]
I've tried with qemu emulation at one point and compilation took a loooong time

**Comment by ilayn** [comment]
I found this saying arm64 is supported by Azure but am I missing the point ? 

https://azure.microsoft.com/en-us/updates/azure-devops-pipelines-introduces-support-for-linuxarm64/

**Comment by mattip** [comment]
They don't say it outright, but some trials point to Azure support for arm64 being a qemu emulation right now, which would definitely timeout before being useful.

**Comment by andyfaff** [comment]
>  qemu emulation right now, which would definitely timeout before being useful.

Most CI agents allow multi-stage runs; one stage could be build, and one testing. Each stage gets the full time. However, the build stage might still not finish in the time allowed.

**Comment by rgommers** [comment]
That's definitely still going to time out. We only got it within an hour on TravisCI with a lot of trouble, and that's using the Graviton2 processors I believe, which are way faster than other aarch64 options on CI.

**Comment by andyfaff** [comment]
Why does the build process take so long? Are arm processors just slow at compiling, or is the compiler toolchain just not as developed.
The arm setup on travis may have room for improvements. I believe both the arm matrix entries do a build and test, but just split the tests into two. If one stage did the build, the stage that follows doesn't need to build, it can just do the tests.

**Comment by andyfaff** [comment]
https://docs.travis-ci.com/user/build-stages/

However, I'm reluctant to try getting that to work now, developing CI scripts can burn a lot of time.

**Comment by rgommers** [comment]
>  Are arm processors just slow at compiling

They're just slow in general - running the test suite takes significantly longer than building. That's why the tests are split in two groups.

>  If one stage did the build, the stage that follows doesn't need to build, it can just do the tests.

That won't be faster for the second stage.

It works now without timing out, and the build + test is heavy enough that it definitely cannot be moved to something like Azure + qemu. So there's no point to mess with it I think.

Drone would be the next-best option. But IIRC that still wasn't fast enough (and would add yet another CI provider).

**Comment by ilayn** [comment]
OK then until things move forward in CI world then let's consider this as done. We can always come back at it when situation improves.

**Comment by mckib2** [comment]
> I've tried with qemu emulation at one point and compilation took a loooong time

Re qemu: why not cross-compile then run tests with qemu?  Compiler does the same amount of work presumably, I'm not sure how fast the tests would run in comparison, but that would seem to solve the long compilation times problem

**Comment by rgommers** [comment]
That may work, maybe. Cross-compilation isn't officially supported by (`numpy.`)`distutils`; things have imroved a bit recently, but I'm not sure if cross-compilation to ARM64 will work without build system patching.
