### ISSUE TITLE
Performance of scipy.stats.qmc

### ISSUE THREAD

**Issue by tupui** [scipy/scipy#13474]
Now that there is a `scipy.stats.qmc` module thanks to #10844, it might be worth looking into moving some of the critical parts to either Cython or Pythran.

Candidates:
* `scipy.stats.qmc.Sobol` is already calling some Cython code. But we are using some types which restrict us 30 bits (we can sample up to `n=2**30` points), having a way to handle more bits would be great as we could sample more points with the method. It might require to have an option to select in order to not penalize the speed. We could also add a check around this limitation, it should be fast. #15647
* `scipy.stats.qmc.LatinHypercube` and `scipy.stats.qmc.Halton` are in python.
* `scipy.stats.qmc.discrepancy` would be of great value to optimize. Most function are already python-optimized (vectorized numpy), but these are important functions in an optimization context. If someone wants to generate sample candidates and wants to calculate the discrepancy, it is important to have a fast implementation here.

Work in progress:
- [x] `scipy.stats.qmc.discrepancy` (in progress in #13576)
- [ ] `scipy.stats.qmc.Sobol` (some cleaning in #13514, more in #15647)
	- [ ] 	Only load a fraction of the direction numbers in Sobol'.
- [x] `scipy.stats.qmc.Halton`
- [x] Van der Corput sequence #14449
- [ ] `scipy.stats.qmc.LatinHypercube`
- [x] ~`scipy.stats.qmc.OrthogonalLatinHypercube`~  (Implementation was incorrect #13647 and removed. Has to be implemented from scratch, discussions in #13659)
- [x] Add benchmarks (done for `discrepancy`, `Sobol`, `Halton`)

**Comment by V0lantis** [comment]
Working on it with @Carreau and @jb-leger

**Comment by tupui** [comment]
> Working on it with @Carreau and @jb-leger

Great 👍 Thanks for picking this up.

@Balandat this might interest you.

**Comment by tupui** [comment]
For reference, I made a comment here about things I did a while ago with the discrepancy: https://github.com/scipy/scipy/pull/10844#discussion_r558010979

**Comment by endolith** [comment]
From the mailing list:

> > For example, I was toying with
> the idea of removing `array_like` input from stats.qmc before we release
> it, and just accept plain ndarrays (has other benefits, but removes
> overhead too).
> 
> I am slowly coming to the same conclusion that array_like is not serving
> the convenience it promises other than the trivial `[1, 2, 3]` type of
> array inputs. And we are losing much of the performance in these checks
> especially when the functionality is an order of magnitude faster than
> these checks. Instead of checking the ndim and be done with it we are doing
> lots of things for the array_like edge cases.

Can array_like cases be treated as exceptions?  We always follow the "Look Before You Leap" model of converting to arrays and checking dimensions, etc. explicitly.  But we could be following the "Easier to Ask for Forgiveness than Permission" model more often?  

For instance, scipy.stats.qmc.scale starts with

```
sample = np.asarray(sample)
...
if not sample.ndim == 2:
```

Instead, you could check sample.ndim inside a try..except "and be done with it", only calling np.asarray in the exceptional case that there's an AttributeError and an array_like needs to be converted.  Then do the conversion to array (slowly) and try the same thing again.

I imagine this could be done for many of the functions that convert array_like inputs as the first step?  Then, for the typical array cases, the performance will be fast, skipping any conversion, and for the usual array_like use case of entering lists by hand in the interpreter, the extra time spent in the exception is irrelevant, and it still works.

**Comment by tupui** [comment]
@endolith I totally agree. There is definitely something to do with respect to data validation in general. I will create an issue so we can keep track of this. A thorough reflection on the problem could be an interesting GSoC project.

**Comment by andyfaff** [comment]
`np.asanyarray`?

**Comment by endolith** [comment]
On my machine, `asarray` and `asanyarray` both take 300 ns if it's already an array, while something like arr.ndim takes 40 ns.   So 340 ns to always convert and then get ndim, vs 40 ns to just get ndim and then convert only when that fails.  

It would be good to have an example of a function where "the functionality is an order of magnitude faster than
these checks" for comparison purposes.  Inner loops of optimization I think was mentioned somewhere?

**Comment by tupuinui** [comment]
@endolith for the optimization part, I refered to #13629. So `cdist` functions.

**Comment by tupui** [comment]
@endolith for the optimization part, I refered to #13629. So cdist functions.

**Comment by andyfaff** [comment]
> On my machine, asarray and asanyarray both take 300 ns if it's already an array, while something like arr.ndim takes 40 ns. So 340 ns to always convert and then get ndim, vs 40 ns to just get ndim and then convert only when that fails.

300 ns/ 40 ns are not large amounts of time. I would posit that if they're an issue it's because there's an architecture problem somewhere. For example, they shouldn't be called in an inner loop, but only on initial entry to a public function.

Often vectorisation helps, sometimes that needs to be done in scipy, sometimes the user needs to vectorise their code.

**Comment by treverhines** [comment]
@tupui I can take a stab at cythonizing `Halton` if no one has already started working on that.  My plan is to replace this line https://github.com/scipy/scipy/blob/59b4a29577e120ee792185ce9716cfd839ca8c33/scipy/stats/_qmc.py#L512  
with a for loop since the number of iterations can be determined from `base` (I think the number of iterations is something like `ceil(54/log2(base))`).  Knowing the number of iterations, you can allocate the random permutations outside of the loop, leaving everything inside the loop for C.   Also, fewer iterations are needed when `scramble` is `False`, and I can take that into account.

**Comment by V0lantis** [comment]
> @tupui I can take a stab at cythonizing `Halton` if no one has already started working on that. My plan is to replace this line
> 
> https://github.com/scipy/scipy/blob/59b4a29577e120ee792185ce9716cfd839ca8c33/scipy/stats/_qmc.py#L512
> 
> 
> with a for loop since the number of iterations can be determined from `base` (I think the number of iterations is something like `ceil(54/log2(base))`). Knowing the number of iterations, you can allocate the random permutations outside of the loop, leaving everything inside the loop for C. Also, fewer iterations are needed when `scramble` is `False`, and I can take that into account.

I tried, but it was rather harder than I thought, and I gave up. I wanted to gave it a look back, but didn't find anytime, so feel free :-)

**Comment by tupui** [comment]
> @tupui I can take a stab at cythonizing `Halton` if no one has already started working on that.  

Thank you @treverhines! I know that @V0lantis looked at it, but there is no open PR. I would suggest you get it touch with each other to work on this.

**Comment by tupui** [comment]
Halton is now in Cython. We might increase performance by leveraging parallelization on `d` and `n`.
