### ISSUE TITLE
tracking issue for Gitpod integration

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#13677]
Prebuild works now, I'm developing in Gitpod to get a better sense of workflow and finding remaining issues. A tracking issue seems helpful for what we know is still TODO, and tweaks that need to be made.

Main TODOs:

- [x] documentation on how to use it (and ideally the prominent button too)
- [ ] ensuring that the most recent prebuild is picked when navigating to https://gitpod.io/#https://github.com/scipy/scipy. Right now it looks like after a merge to master, the previous prebuild is not picked up. See https://github.com/scipy/scipy/pull/13667#issuecomment-794463176 for details.
    EDIT: asked for advice at https://community.gitpod.io/t/using-the-most-recent-prebuild-may-be-behind-head/2980
- [x] see if we can name `scipy/scipy` as `upstream` rather than `origin`, to match our contributor guide (the contributor's own fork is called `origin`). EDIT: may be a non-issue except for people who have commit rights, see second comment below.

Smaller issues/tweaks:

- [x] `.theia/settings.json` has 3 python settings that current give a warning (the IDE claims the settings are unsupported). This is also visible in the sidebar, so it's a little distracting:

<img width="598" alt="image" src="https://user-images.githubusercontent.com/98330/111042469-dc5ebd80-843d-11eb-909a-02f353fba20d.png">

- [x] the scipy and docs prebuilds work, and `runtests.py` does the right thing. however re-running `make html` for the docs doesn't, because `conda develop .` doesn't manage to include `scipy` in the list of installed packages. need to look into whether that can be improved.
- [x] on each new workspace startup, there's a popup "Sphinx preview not enabled". This is probably because a workspace opens with `README.rst` opened up in Theia by default. Would be nice to install a Sphinx extension, but I don't see one.

Other ideas:

- [x] integrate the `gh` tool (https://github.com/cli/cli), very useful for working with PRs and collaborating with others.

Cc @trallard

**Comment by rgommers** [comment]
> the scipy and docs prebuilds work, and `runtests.py` does the right thing. however re-running `make html` for the docs doesn't, because `conda develop .` doesn't manage to include `scipy` in the list of installed packages. need to look into whether that can be improved.

found it, `conda develop .` creates a `conda.pth` file in `/opt/conda/envs/scipydev/lib/python3.8/site-packages/`, and when that's done in the prebuild step that file goes missing. Pip gets special-cased by Gitpod it looks like, so `pip install somepkg` installs to `/workspace/.pip-modules/lib/python3.8/site-packages`. Everything that gets added in prebuild should be something in `/workspace`. Maybe executing `conda develop .` during startup again will help (it works as expected when you run it in the terminal).

**Comment by rgommers** [comment]
For the `origin` vs. `upstream` issue, https://community.gitpod.io/t/how-to-specify-users-fork-instead-of-main-repository/639 suggests letting people start from their own forks. That gets the names right, but it fails to pick up the prebuilds (because those are only connected to the main repo) - so that doesn't help.

**Comment by rgommers** [comment]
For the prebuild issue, @thomasjpfan made a good suggestion on the Gitpod Discourse:
_I think a possible work around is to create a Docker image with scipy-dev + build dependencies (using github actions nightly), upload it to DockerHub, and config .gitpod.yml to use that image. This way, the prebuilds would only need to fetch the image from DockerHub without actually needing to build scipy._

I'm not 100% sure we want to make those changes for SciPy (we have no sprint planned), although it's not that much work probably - but for NumPy we should try to set it up that way before the sprint in May. Maybe inventing that wheel for NumPy and syncing it back to SciPy is the optimal order.

**Comment by trallard** [comment]
I have been meaning to add to this issue:
- I can do some work on the paths to ensure stuff is persisted (mostly the `conda develop .` step)
- Following on @thomasjpfan  I did think about that given that now you can use a prebuilt Docker image altogether (a few weeks back you still had to create a `.gitpod.Dockerfile` but I have been thinking on doing the changes so that we have the following setup:
  - base image (currently in SciPy Dockerhub) to only be rebuilt and pushed when dev dependencies are updated (from the environment.yaml file)
  - do a nightly build on the gitpod Docker image to include the SciPy built I am, however, a bit unsure if we would be able to also include the docs build due to CI timeouts (need to double-check as this can take quite a while)
  
  This should be low effort - and I/we should be able to make a quick implementation in NumPy before the sprint. I can do this on Friday and have a PR ready then. Does this sound good?

**Comment by rgommers** [comment]
This sounds great. If the docs build doesn't fit, we can leave that for later since it's less important than always having a prebuilt image available. But I suspect it does fit, because it's shorter than running the test suite - and we don't have to run the test suite when building this Docker image.

**Comment by rgommers** [comment]
This was all fixed, just checked again in preparation for the sprint, and everything works like a charm. Thanks again @trallard!

**Comment by WarrenWeckesser** [comment]
Ping @rgommers, @trallard: `quickstart_gitpod.rst` links to [Development workflow](http://scipy.github.io/devdocs/dev/contributor/development_workflow.html), and that document says

> In [Development environment quickstart guide (macOS)](http://scipy.github.io/devdocs/dev/contributor/quickstart_mac.html#quickstart-mac) or [Development environment quickstart guide (Ubuntu)](http://scipy.github.io/devdocs/dev/contributor/quickstart_ubuntu.html#quickstart-ubuntu), you created your own fork (copy) of the SciPy repository, cloned the repository on your own machine, and built SciPy from this source code.

The Mac and Ubuntu quickstart guides tell you to install Anaconda and create a conda environment for development (e.g. `conda create --name scipydev python=3.8 numpy pybind11 cython pythran pytest gfortran_linux-64 gxx_linux-64 sphinx pydata-sphinx-theme sphinx-panels matplotlib mypy git`.  I assume those steps are not actually needed in gitpod,  since we already create a `scipy-dev` environment, and scipy is built the first time a gitpod workspace is fired up.  Is that correct?

**Comment by trallard** [comment]
That is correct 😁 I linked to development workflow to reference the sections from "Basic workflow onwards" if this is not obvious or is likely to confuse folks. 

Basically once Gitpod is up and running folks can start hacking away as it is a full Dev environment + git is already configured as folks log in through GitHub.

**Comment by WarrenWeckesser** [comment]
Thanks @trallard.

At the end of the section "Making a new feature branch" in  [Development workflow](http://scipy.github.io/devdocs/dev/contributor/development_workflow.html), there is

> It’s also a good idea to build this branch and run tests before continuing. Assuming you’ve followed Development environment quickstart guide (macOS) or Development environment quickstart guide (Ubuntu) to set up your development environment, you’ll need to activate your development virtual environment, perform an in-place build, and run tests:
>
>      conda activate name-of-your-virtual-environment
>      python setup.py build_ext --inplace
>      python runtests.py -v

The command `conda activate ...` should be skipped--we are already in a development environment when we're using gitpod (correct?).

**Comment by trallard** [comment]
Yes the `scipy-dev` env is always activated so this can be skipped. 

Do you peeps think it would be best to do extend the workflow section to cover branches creation etc. Rather than linking to the existing section to avoid confusion? 

If so this is something I can do and send over

**Comment by WarrenWeckesser** [comment]
At the moment, I'm not sure. I'm still getting up to speed on the basics of using gitpod, so I don't have any immediate recommendations.
