### ISSUE TITLE
ENH: Improvements for `scipy.stats.qmc`

### ISSUE THREAD

**Issue by tupui** [scipy/scipy#14510]
This is a general issue to track feature improvements ideas/plans for the `scipy.stats.qmc` submodule. For performance, check sibling issue #13474 instead.

## New methods
- [ ] Poison disk sampling #13918
- [ ] Lloyd's algorithm https://github.com/stefanv/lloyd/issues/2
- [ ] Orthogonal LHS: strength 2 in #13659
- [ ] Optimal LHS: basic method in #13471

## Doc and usability
- [ ] Tutorial sampling with QMC and any distribution (`scipy.stats.NumericalInverseHermite`)
- [ ] Hammersley sequence

## Improvements
- [ ] Augment LHS
- [ ] Other scrambling methods for Sobol' and Halton
- [ ] Other metrics (l1, l2, linf, MST, etc.) #14037

**Comment by tupui** [comment]
@bashtage since you did `randomgen`, maybe you would have inputs on the following item. I am sure there are more things to factor in.

Right now for Sobol', I would just change the types to allow this, but first I am not sure how to do it optimally (without duplicating the code if we want to have 2 different handling of types) and if this makes sense. For Halton and LHS, I am not sure what are the limitations.

> Allow sampling above 2^30 points in Sobol' (work on types, current types can already work with 2^31 - 1). Optional `dtype` argument like NumPy can be an option. I would accepts `np.float32` or `np.float64` to produce either single or double prevision uniform random variables.
