### ISSUE TITLE
BUGS: stats: Tracking issue for distributions that warn and/or return nan at support endpoints 

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#15195]
In this test:

https://github.com/scipy/scipy/blob/c9cdbf2804d092eb63dc66e885ca99af11f381e5/scipy/stats/tests/test_continuous_basic.py#L549-L573

`RuntimeWarning`s that occur when evaluating a distribution at an endpoint of the support are filtered out.

Each such occurrence of a `RuntimeWarning` is a bug.  Eventually we should be able to remove the filtering, because the distributions should not generate a `RuntimeWarning`.

This is the list of distributions that generated warnings when I removed the filtering and ran the tests.  This serves as a task list for bugs to be fixed:

- [x] cosine  (PR: https://github.com/scipy/scipy/pull/15196)
- [ ] gausshyper
- [ ] genextreme
- [x] gengamma (PR: https://github.com/scipy/scipy/pull/15196)
- [ ] genhalflogistic
- [ ] ksone
- [ ] kstwo
- [ ] kstwobign
- [ ] loglaplace
- [ ] maxwell
- [ ] mielke
- [x] recipinvgauss (PR: https://github.com/scipy/scipy/pull/15194)
- [ ] rice
- [ ] semicircular
- [ ] trapezoid
- [ ] triang
- [ ] distname

### SciPy/NumPy/Python version information

1.9.0.dev0+1049.c9cdbf2 1.21.2 sys.version_info(major=3, minor=9, micro=5, releaselevel='final', serial=0)
