### ISSUE TITLE
META: deprecation tracker

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#15765]
### _Please edit this tracker as necessary_

Apologies for bombing the issue tracker with lots of outstanding deprecations, but it felt like some necessary housekeeping. 🙃 

Below a list of deprecations by kind and scipy release. Ideally - in my opinion at least (and this is what I propose to use this issue for) - all _**deprecations should come with an announced behaviour change, and with an announced timeframe**_ (i.e. scipy version where things will be changed/removed), and other items migrated there as appropriate.

As the list below shows, this is a trend that started only relatively recently, with removal/behaviour change in `1.(N+2)` if a given deprecation is introduced in `1.N`. Still, I think that's a reasonable policy.

### Deprecations in documentation only

Need to add proper deprecation warnings. This list is likely incomplete

* 0.10
  * [ ] #15748
* 0.19
  * [ ] #15735

### Deprecated without announced removal

Sharpen warning to announce removal in 1.10/1.11, or remove directly in 1.9, depending.

* 0.13
  * [ ] #15764
* 0.15
  * [ ] #15733
* 0.16 
  * [ ] #15755
* 0.17 
  * [ ] #15758
* 0.18
  * [ ] #15751
* 0.19
  * [ ] #15734
  * [ ] #15736
  * [ ] #15752
  * [ ] #15754
  * [ ] #15759
* 1.0
  * [ ] #15741
  * [ ] #15742
  * [ ] #15753
  * [ ] #15760
* 1.1
  * [ ] #15732
  * [ ] #15738
  * [ ] #15745
  * [ ] #15761
* 1.3 
  * [ ] #15757
* 1.4 
  * [ ] #14889
  * [ ] #15743
* 1.5
  * [ ] #15747
  * [ ] #15762
* 1.7
  * [ ] #15737
* 1.8
  * [ ] #15744
  * [ ] #15749
* 1.9
  * [ ] #15739

### Removal announced, missed

* 1.5 (announced removal for 1.7)
  * [ ] #15731
* 1.6 (announced removal for 1.8)
  * [ ] #15746
  * [ ] #15750

### Removal announced in `1.N` for `1.(N+2)`

* 1.7 (announced removal for 1.9)
  * [ ] #15740
* 1.9 (announced removal for 1.11)
  * [ ] #15722
  * [ ] #15707
  * [ ] #15706
  * [ ] #15756

### Outstanding deprecations

List most likely incomplete

* [ ] #5676
* [ ] #14494
* [ ] #15125

### Outstanding behaviour changes

List incomplete (and intentionally so; not every tiny _planned_ change needs to be here from the get go; but do add it if desired, ideally already above with a direct action item).

* [ ] #1408
* [ ] #2011
* [ ] #3259
* [ ] #3343
* [ ] #3590
* [ ] #4063 / #5348
* [ ] #4818
* [ ] #5266
* [ ] #6006
* [ ] #6137
* [ ] #8923
* [ ] #10419
* [ ] #11334
* [ ] #11991
* [ ] #13632
* [ ] #14039
* [ ] #14322
* [ ] #14494
* [ ] #14714
* [ ] #15608
* [ ] #15600 - deprecate legacy behaviour in factorial functions
* [ ] #15702

**Comment by tupui** [comment]
Hi @h-vetinari, thanks for compiling this list! I would not have created issues for all of them, but kept a list and use GH's features to then create/link PRs when something is on the way. This to prevent spamming people following the repo.

**Comment by h-vetinari** [comment]
Understood, though I think text in an issue somewhere quickly gets forgotten (and discussing individual cases in a meta/mega-tracker quickly gets impossible to follow).

OTOH, if it's an issue in a milestone, many more people will look at it, with a much higher chance that it gets done (also, we can set "good first issue" labels!). I'm sorry about the spam; at least it should be (have been) a one-time thing; even if we continued to raise individual issues, it'd be incremental from now on.

**Comment by rgommers** [comment]
This is very useful, and will help going through and cleaning this up, thanks @h-vetinari. One minor comment: the abbreviation we use is `DEP:` rather than `DEPR:`. For consistency, it may be useful to remove that now, otherwise we'll end up with mixed acronyms long-term.

**Comment by h-vetinari** [comment]
> One minor comment: the abbreviation we use is `DEP:` rather than `DEPR:`

Sorry about that. My first instinct when choosing such acronyms is to avoid ambiguity (such as "dep" for depencency management), but I didn't know that this was standardized already (is there a list somewhere?). In any case, I can change this in the issue titles (of those I raised). If we're consistent with the `deprecate` label, that schism will be even less of a problem.

**Comment by tupui** [comment]
> ... (is there a list somewhere?). 

Yes the list is here https://scipy.github.io/devdocs/dev/contributor/development_workflow.html#writing-the-commit-message

**Comment by h-vetinari** [comment]
Great thanks! (I was looking through the templates and the wiki here...)

**Comment by j-bowhay** [comment]
@h-vetinari another warning that doesn't state version to be removed https://github.com/scipy/scipy/blame/main/scipy/io/harwell_boeing.py

**Comment by h-vetinari** [comment]
Thanks @j-bowhay. I've excluded all the module-level deprecations that came from the work in #14360 above; I think we should track a timeline for removal, but I'm not sure when that's planned...

**Comment by h-vetinari** [comment]
Now that 1.9 has branched, I removed the work done for that release from the tracker. Here it is for the purpose of record-keeping:

### Deprecations that were executed for 1.9

* 0.13
  * [x] #15764
* 0.17 
  * [x] #15758 (see also #5266)
* 0.18
  * [x] #15751
* 0.19
  * [x] #15734
  * [x] #15736
  * [x] #15752
  * [x] #15754
  * [x] #15759
* 1.0
  * [x] #15741
  * [x] #15742
  * [x] #15753
  * [x] #15760
* 1.1
  * [x] #15732
  * [x] #15745
  * [x] #15761
* 1.3 
  * [x] #15757
* 1.4
  * [x] #14889
  * [x] #15743
* 1.5
  * [x] #15747
  * [x] #15762
* 1.6 
  * [x] #15746 (removal had been announced for 1.8)
  * [x] #15750 (removal had been announced for 1.8)
* 1.7
  * [x] #15737
  * [x] #15740 (removal had been announced for 1.9)

### Old deprecations, warning sharpened for removal in 1.10/1.11

* 0.10
  * [x] #15748
* 0.12
  * [x] #16255
* 0.19
  * [x] #15735
* 1.5
  * [x] #16254
* 1.8
  * [x] #15744
* 1.9
  * [x] #15739

**Comment by tupui** [comment]
Thank you again @h-vetinari, this is great work and very useful 👏

**Comment by ev-br** [comment]
Edited in the interp2d deprecation plan from gh-17180 and the related mailing list discussion.

**Comment by j-bowhay** [comment]
Maybe this would be a nice issue to pin for better visibility?

**Comment by h-vetinari** [comment]
Since 1.10 just branched, here's the things we did for 1.10 (now removed from the tracker)

### Removed in 1.10

* 0.12
  * [x] #16251 
* 0.15
  * [x] #15733 (deprecation itself was undone; hence no release note)
* 1.7
  * [x] #16395
* 1.8
  * [x] #15749
  * [x] #15807

### Deprecated in 1.10, removal announced for 2.0

* [x] #15608

### Old deprecations, warning sharpened for removal in 1.11/1.12

* 0.11
  * [x] #16392
* 0.18
  * [x] #16388
* 1.0
  * [x] #16253
* 1.5
  * [x] `scale='raw'` in `iqr` (see #16389)
  * [x] #16252
* 1.7
  * [x] #16256
* 1.9
  * [x] `n` in `stats.moment` and `alpha` in `stats.interval` (see #16389)

**Comment by h-vetinari** [comment]
Since 1.11 just branched, here's the things we did for that release (now removed from the tracker)

### Removed in 1.11


* 0.10
  * [x] #15818
* 0.12
  * [x] #16270
* 0.16 
  * [x] Non-uniform timestamps in `lsim` (see [here](https://github.com/scipy/scipy/pull/4675) & [here](https://github.com/scipy/scipy/issues/15755)) 
* 0.19
  * [x] #15829
* 1.5
  * [x] #16269
* 1.9
  * [x] Switched default of `legacy=` kwarg in `special.comb` (see [here](https://github.com/scipy/scipy/issues/15722))
  * [x] #15706
  * [x] #15756
  * [x] #15808
  * [x] #15988
  * [x] #16014
  * [x] #16271
  * [x] removal of kwargs `n` in `stats.moment` and `alpha` in `stats.interval` (follow-up to [this](https://github.com/scipy/scipy/pull/13490) and [this](https://github.com/scipy/scipy/pull/16389))
  * [x] #18290

### Old deprecations, warning sharpened for removal in 1.12/1.13


* 0.16
  * [x] #5676
  * [x] #15755
* 1.1
  * [x] https://github.com/scipy/scipy/issues/18484
* 1.3
  * [x] https://github.com/scipy/scipy/issues/18485

### New deprecations

* 1.11
  * [x] #17455
  * [x] #18021
  * [x] `even` keyword in `scipy.integrate.simpson` (see [here](https://github.com/scipy/scipy/pull/18209)) 
  * [x] #18290
  * [x] #18341
  * [x] #18507

**Comment by j-bowhay** [comment]
Work completed for this release:

### Old deprecations, warning sharpened for removal in 1.13/1.14

* 0.11 (version where original deprecation was added)
  * [x] #18577
* 0.19 (as above...)
  * [x] #18578
* 1.0
  * [x] #18579
* 1.6 
  * [x] #18702
* 1.8
  * [ ] #18279 (more a clarification, but noted for completeness)

### New deprecations

* 1.12
  * [ ] #18703 (for any deprecation that will result in changes to a function signature)
    * [x] #18932
    * [x] #18933 
    * [x] #18934 
    * [x] #18935 
    * [x] #18936
    * [x] #18943
    * [x] #18946
  * [x] #18587
  * [x] #18219
  * [x] deprecate `scipy.stats.rvs_ratio_uniforms` (in #18622)
  * [x] #19340 
  * [x] #19510

### Removed for 1.12

* 1.5 (version where original deprecation was added; raises DeprecationWarning as of 1.10)
  * [x] #18580
* 1.7
  * [x] #18581
* 1.10
  * [x] #18582

**Comment by lucascolley** [comment]
@j-bowhay probably useful to have gh-18703 linked somewhere in the top comment?

**Comment by h-vetinari** [comment]
> Work completed for this release:

Since you took care of most of the tracking this cycle, could you open a PR that ensures the release notes ([already](https://github.com/scipy/scipy/blob/v1.12.0rc1/doc/source/release/1.12.0-notes.rst) on the 1.12 branch) are up-to-date? For example, I see that not all expired deprecations are listed.

**Comment by lucascolley** [comment]
For executing the deprecations of things that were never supposed to be public like gh-19801 for 1.13.0, is that going to be done per module @j-bowhay ? I have no idea how many there are.

**Comment by j-bowhay** [comment]
I was planning to do it all at once, I think it should be a case of just tweaking the helper and removing things until the tests are happy.

**Comment by h-vetinari** [comment]
In #19880, there was some discussion around deprecations, as the "out-of-band" release of 1.13 throws a bit of a wrench into the deprecations as they've been laid out (on the basis of a 6 month release cadence).

@rgommers noted:
> Please consider following https://numpy.org/neps/nep-0023-backwards-compatibility.html#implementing-deprecations-and-removals for future deprecations though, it works pretty well in NumPy.

We do follow that pretty much to a tee, with the exception that we started putting version numbers for scheduled removal in the warnings (that aspect does not seem mandated either way by NEP23), and that we don't have "is deprecated since" bit.

I do think the removal date is user-relevant (despite the fact that we don't know the future); by seeing the warning, they're obviously already on an affected version, so when it was introduced is less relevant.

That said, it's IMO fine to switch to a "deprecated as of" formulation, as that avoids the need for a crystal ball. That way we can always wait for a year before removal - though in turn, we shouldn't revert back to the bad old days of letting these deprecation warnings linger indefinitely.

---

For the here and now (and especially given that 1.12 hasn't been released yet), we should double-check current deprecations that we don't remove things too early/eagerly. Looking at the [list above](https://github.com/scipy/scipy/issues/15765#issuecomment-1849036232), a lot of them had been deprecated previously already (or we even extended the deprecation period due to _also_ deprecating positional use), so the only ones where I think it makes sense to push the announced deprecation date from 1.14 to 1.15 (or reformulate the warning completely) are the following:

* new deprecations in 1.12:
  * [x] #18587
  * [x] #18219
  * [x] deprecate `scipy.stats.rvs_ratio_uniforms` (in #18622)
  * [x] #19340 
  * [x] #19510

For things deprecated in 1.11 and already removed on `main`, the emerging consensus was to leave these things as-is. The only exceptions are #18583 (delayed to 1.14, see discussion in #18618), #19673, resp. the follow-up to #18507; for the latter two we should decide what we want to do; I think it'd be easiest just to wait.

I'll prepare a PR for the 1.12 backport.

**Comment by j-bowhay** [comment]
Work completed for the 1.13 release:
### New deprecations

- [x] https://github.com/scipy/scipy/commit/18bb04b95df98d5264bd3e522b8adde916f17e05
- [x] #19752

### Removal announced for 1.13
- [x] #19675 (follow-up of [this](https://github.com/scipy/scipy/issues/5676), [this](https://github.com/scipy/scipy/issues/15755) & [this](https://github.com/scipy/scipy/pull/15929)) 
- [x] #19676 (follow-up of [this](https://github.com/scipy/scipy/pull/18489)) 
- [x] #18541 (follow-up of [this](https://github.com/scipy/scipy/pull/18540))
- [x] #19672 (follow-up of [this](https://github.com/scipy/scipy/pull/17455)) 
- [x] #19674 (follow-up of [this](https://github.com/scipy/scipy/pull/18021)) 
- [x] https://github.com/scipy/scipy/commit/f5265e529c088f9affbeb7d9698dbcb48821c58f (follow-up of [this](https://github.com/scipy/scipy/pull/15841))

**Comment by tylerjereddy** [comment]
@h-vetinari I proposed the SciPy `1.14.0` release schedule here: https://discuss.scientific-python.org/t/proposed-release-schedule-for-scipy-1-14-0/1151?u=tylerjereddy

**Comment by h-vetinari** [comment]
Now that 1.14 has branched, here's what we did. This is the last release where we clean out a lot of the cruft that took a while to deprecate (some of which got pushed back by various things). From now on, we should be doing quite a bit better. :)

### New deprecations

- [ ] #20486 (will be finished before GA)
- [x] #15722
- [x] #20283
- [x] #20716
- [x] #20753

### Removal announced for 1.14



* 0.11 (version where original deprecation was added) 
  - [x] #20498 (follow-up to [this](https://github.com/scipy/scipy/pull/16392) & [this](https://github.com/scipy/scipy/pull/18934))
* 0.19 (as above...)
  - [x] gh-20550 (follow-up to [this](https://github.com/scipy/scipy/issues/16388) & [this](https://github.com/scipy/scipy/pull/18936))
* 1.0
  - [x] #20578 (follow-up to [this](https://github.com/scipy/scipy/pull/16315) & [this](https://github.com/scipy/scipy/pull/18932))
* 1.5
  - [x] #20560 (follow-up to [this](https://github.com/scipy/scipy/pull/16355) and [this](https://github.com/scipy/scipy/pull/18946))
* 1.6
  - [x] #20278 (follow-up to [this](https://github.com/scipy/scipy/pull/18699))
* 1.7
  - [x] #20565 (follow-up to [this](https://github.com/scipy/scipy/pull/18812) and [this](https://github.com/scipy/scipy/pull/18935))
* 1.10
  - [x] #20497
* 1.11
  - [x] https://github.com/scipy/scipy/pull/20588 (basically [this](https://github.com/scipy/scipy/issues/15722) + [this](https://github.com/scipy/scipy/pull/18933); [delayed](https://github.com/scipy/scipy/pull/18624) from 1.13 to 1.14)
  - [x] #20554 (follow-up to [this](https://github.com/scipy/scipy/pull/18209) & [this](https://github.com/scipy/scipy/pull/18843); [delayed](https://github.com/scipy/scipy/pull/18624) from 1.13 to 1.14)
  - [x] #19673 (follow-up to [this](https://github.com/scipy/scipy/pull/18341)) 
* 1.12
  - [x] #19904
  - [x] #20499 (follow-up to [this](https://github.com/scipy/scipy/pull/18507))
  - [x] #20498 (follow-up to [this](https://github.com/scipy/scipy/pull/18934), [this](https://github.com/scipy/scipy/pull/18943) and [this](https://github.com/scipy/scipy/pull/19702))

**Comment by lucascolley** [comment]
@mdhaber did you mean to unpin this? Fine if so, I was just wondering where it had gone for a second.

**Comment by mdhaber** [comment]
Oops, no, I didn't mean to!

**Comment by tylerjereddy** [comment]
@fancidev have you seen this deprecation tracking issue? We should probably update it a bit for the deprecations getting introduced in `spatial` so I don't incur the wrath of the organized folks here :)

**Comment by fancidev** [comment]
> @fancidev have you seen this deprecation tracking issue? We should probably update it a bit for the deprecations getting introduced in `spatial` so I don't incur the wrath of the organized folks here :)

Thanks for reminding. I have seen the pinned issue but wasn’t sure what it was intended for.

There are three deprecations in spatial (in two PRs):

gh-21085
gh-21572

Shall I append them to the “New Deprecations” section?

**Comment by j-bowhay** [comment]
I have updated the tracker but please could you check the release notes are up to date

**Comment by h-vetinari** [comment]
> so I don't incur the wrath of the organized folks here :)

No wrath whatsoever, we're just trying to stay on top of deprecations, so they don't get forgotten. :)

> Shall I append them to the “New Deprecations” section?

As a maintainer, feel free to edit the tracker, but please follow the notes (e.g. add new deprecations twice - once for this release, and once as a reminder to execute in the future)

**Comment by dschmitz89** [comment]
Looks like we missed the scheduled deprecation of `special.btdtr` and friends for 1.14: https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.btdtr.html

Where should I add that in the tracker?

**Comment by h-vetinari** [comment]
> Where should I add that in the tracker?

Best approach is to open an issue (incl. reference to PR that did the original deprecation), label it "good first issue", and then put it under the "Removal announced, missed" section.

Or, if you want to do it directly, just open a PR that executes the removal, and then reference that PR under the section of stuff we've done for this release (with a note that it was originally scheduled for removal in 1.14).

**Comment by j-bowhay** [comment]
@dschmitz89 Is this related to #15596?

**Comment by dschmitz89** [comment]
> @dschmitz89 Is this related to #15596?

Related. `btdtr` and the others are completely replaced by `betainc` etc. . For most other statistical functions in `special`, we can and should move to boost though.

**Comment by mdhaber** [comment]
Does anyone recall why the functions in `scipy.misc` didn't appear here or why they haven't been removed? I've reviewed some of the issues and although there was talk about leaving the `misc` namespace until 2.0, all the functions inside it were decorated in 1.10 and slated for removal in 1.12.

**Comment by andyfaff** [comment]
See #21864

**Comment by mdhaber** [comment]
gh-21864 brings up the following:

```python3
from scipy.interpolate.rbf import Rbf
# <ipython-input-16-bdbe73d5c0de>:1: DeprecationWarning: Please import `Rbf` from the `scipy.interpolate` namespace; 
# the `scipy.interpolate.rbf` namespace is deprecated and will be removed in SciPy 2.0.0.

import scipy.interpolate.rbf
# <no output>
```

Is it OK that there is no warning about removal in 2.0.0 upon import of the module?

It is not so unusual: when we deprecate a function, we typically only emit deprecation messages when the function is called, not when it is imported. If a user were to import a function but never use it, they would never see a deprecation message, and suddenly the function would disappear.

We went a bit beyond that with the warning above when the user imports `Rbf` from `scipy.interpolate.rbf` (and with https://github.com/scipy/scipy/blob/43fc97efa8a617038281e035f8efbc95a96ebff8/scipy/_lib/deprecation.py#L14 in general). This is because the class itself is not deprecated; just the way it was imported. But from that perspective, do we need to go all the way and warn when the module is imported?

In the meantime, we went ahead and added warnings when `misc` or submodules are imported (https://github.com/scipy/scipy/pull/21864#issuecomment-2518679499); the question is whether we should do this for other submodules.

**Comment by j-bowhay** [comment]
I would need to double check but I'm fairly sure if you import as `import scipy.interpolate.rbf` then as soon as you call one of the functions you will get the a warning. The only situation where you wouldn't get warned is if you have unused imports.

**Comment by mdhaber** [comment]
> The only situation where you wouldn't get warned is if you have unused imports.

Yes, I think that's my point. Suppose we decide one of the following:

- "Missing a warning because of an unused import is OK. When the imported feature is removed and the user gets an error, they can simply remove the import." ISTM that this would mean that `import scipy.misc` without warning is OK, and there would be no remaining warning that the module is going to be removed in SciPy 2.0.
- "Missing a warning because of an unused import is not OK. There are no exceptions to the rule that a user must get a warning before a feature is removed." ISTM that this would mean that `import scipy.misc` should indeed warn - as should `import scipy.interpolate.rbf`.

There is a compromise: "Missing a warning because of an unused import is OK _unless_ if the imported feature is unusable (e.g. `scipy.misc`)". But this doesn't seem very principled. This means that `scipy.misc` only exists to announce its own impending removal?

**Comment by h-vetinari** [comment]
Now that 1.15 has branched, here's what we did this cycle:

### New deprecations

- [x] #19223
- [x] finish #19907
- [x] #20558
- [x] #21085
- [x] #21157
- [x] #21211
- [x] #21633
- [x] #21572 
- [x] #21706
- [x] #21754
- [x] #21446

### Removal announced for 1.15

* 1.12 (removal intentionally delayed by one release due to out-of-band 1.13)
  * [x] #20867
  * [x] #20859
  * [x] #20866
  * [x] #20865
  * [x] #20864
  * [x] #21125 (follow-up to [this](https://github.com/scipy/scipy/pull/19060) and incidental imports [clean-up](https://github.com/scipy/scipy/pull/19904))
  * [x] #21759  (removal had been announced for 1.14)
* 1.13
  * [x] #20869 (follow-up to [this](https://github.com/scipy/scipy/commit/18bb04b95df98d5264bd3e522b8adde916f17e05))
  * [x] #20868
  * [x] https://github.com/scipy/scipy/commit/b19bcf36389bf2ef6f7a81229458ee73dd7cec86 (follow-up to [this](https://github.com/scipy/scipy/pull/19716))

**Comment by h-vetinari** [comment]
@j-bowhay @lucascolley, 1.16 has branched, would one of you be able to post a summary (and ensure the release notes capture everything we did related to deprecations)?

**Comment by j-bowhay** [comment]
Here is what we did in 1.16:

### New deprecations

- [x] https://github.com/scipy/scipy/pull/22386
- [x] https://github.com/scipy/scipy/pull/22427

### Removal announced for 1.16

* 1.14
  * [x] #22073 (follow-up to [this](https://github.com/scipy/scipy/pull/20283))
  * [x] #22074 (follow-up to [this](https://github.com/scipy/scipy/pull/20716) and [this](https://github.com/scipy/scipy/pull/20828))
  * [x] #22075 (follow-up to [this](https://github.com/scipy/scipy/pull/20789))
  * [x] #22079 (follow-up to [this](https://github.com/scipy/scipy/pull/20753))
  * [x] #22087 (follow-up to [this](https://github.com/scipy/scipy/pull/20780) and [this](https://github.com/scipy/scipy/pull/20909))
  * [x] #22598 (follow-up to [this](https://github.com/scipy/scipy/pull/20858))

**Comment by j-bowhay** [comment]
Here is what we did for 1.17:
### New deprecations

- [x] #23340
- [x] #23680 
- [x] #24080
- [x] #24033

### Removal for 1.17

* 1.15
  * [x] https://github.com/scipy/scipy/pull/23034  (follow-up to [this](https://github.com/scipy/scipy/pull/20558))
  * [x] https://github.com/scipy/scipy/pull/23202 (follow-up to [this](https://github.com/scipy/scipy/pull/21085))
  * [x] https://github.com/scipy/scipy/pull/23023 (follow-up to [this](https://github.com/scipy/scipy/pull/21157))
  * [x] https://github.com/scipy/scipy/pull/23212 (follow-up to [this](gh-21211) and [this](https://github.com/scipy/scipy/pull/21706))
  * [x] https://github.com/scipy/scipy/pull/23089 (follow-up to [this](https://github.com/scipy/scipy/pull/21446) and [this](https://github.com/scipy/scipy/pull/22193)). At the same time, add batch support (gh-21466).
  * [x] https://github.com/scipy/scipy/pull/23210 (follow-up to [this](gh-21572))
  * [x] https://github.com/scipy/scipy/pull/23043 (follow-up to [this](https://github.com/scipy/scipy/pull/21633))
  * [x] https://github.com/scipy/scipy/pull/23045 (follow-up to [this](https://github.com/scipy/scipy/pull/21754))
  * [x] https://github.com/scipy/scipy/pull/23088 (follow-up to [this](https://github.com/scipy/scipy/pull/21921))
  * [x] https://github.com/scipy/scipy/pull/23243 (follow-up to [this](https://github.com/scipy/scipy/pull/22167) and [this](https://github.com/scipy/scipy/pull/22156) )

**Comment by j-bowhay** [comment]
Here's what we did for 1.18

New depreciations:
- [x] #24060
- [x] #23836
- [x] #24712
- [x] https://github.com/scipy/scipy/pull/24268#issuecomment-3707340886
- [x] #24886 
- [x] #24682 

.Removed for 1.18

  * [x] The `disp` and `iprint` args of the L-BFGS-B are announced to be removed in 1.17 but the warnings were forgotten in #21314 . Hence the deprecation period is extended to 1.18 in #23197 
  * [x] Remove `atol` from `optimize.nnls` (follow-up to [this](https://github.com/scipy/scipy/pull/22386))
  * [x] Remove `disp` from `linalg.{signm, logm, sqrtm}` (follow-up to [this](https://github.com/scipy/scipy/pull/22427))
