### ISSUE TITLE
MAINT: Speed up some slow tests

### ISSUE THREAD

**Issue by larsoner** [scipy/scipy#16494]
In https://github.com/scipy/scipy/pull/16487 several tests are decorated with `@pytest.mark.timeout(120)` because they exceeded 1 minute runtime on at least one CI run -- pinging people based on a rough `blame` look:

- [ ] `scipy/optimize/tests/test_linprog.py : test_mip6` -- #15294 @mckib2 @mdhaber 
- [ ] `scipy/optimize/tests/test_milp.py : test_milp_6` -- #15460 @mdhaber 
- [x] `scipy/sparse/linalg/_dsolve/tests/test_linsolve.py : test_random` -- > 5 years old
- [x] `scipy/sparse/linalg/tests/test_propack.py : test_examples` -- #14433 @mckib2 @tupui 
- [x] `scipy/stats/tests/test_continuous_basic.py : test_moments` for skewnorm -- fixed by #16503
- [x] `scipy/stats/tests/test_continuous_basic.py::test_kappa4_array_gh13582` -- [macOS CI](https://github.com/scipy/scipy/runs/7185604999?check_suite_focus=true)

It would be great to speed these up!

**Comment by WarrenWeckesser** [comment]
@larsoner, https://github.com/scipy/scipy/pull/16503 should fix the slow `test_moments` test for `skewnorm`.

**Comment by tupui** [comment]
This one is making the [macOS CI](https://github.com/scipy/scipy/runs/7185604999?check_suite_focus=true) fail: `scipy/stats/tests/test_continuous_basic.py::test_kappa4_array_gh13582`

**Comment by larsoner** [comment]
@tupui want to open a quick PR to add a `pytest.mark.timeout(120)` or so to that test?

**Comment by mdhaber** [comment]
`scipy/sparse/linalg/_dsolve/tests/test_linsolve.py : test_random` has already been `parametrize`d.
https://github.com/scipy/scipy/blob/26445e52e8c92757b3c45d33e9529c8bbdcc392c/scipy/sparse/linalg/_dsolve/tests/test_linsolve.py#L832-L841

`scipy/sparse/linalg/tests/test_propack.py : test_examples` has already been marked `xslow`.
https://github.com/scipy/scipy/blob/26445e52e8c92757b3c45d33e9529c8bbdcc392c/scipy/sparse/linalg/tests/test_propack.py#L92-L96

`scipy/stats/tests/test_continuous_basic.py::test_kappa4_array_gh13582` has also been marked `xslow`.
https://github.com/scipy/scipy/blob/26445e52e8c92757b3c45d33e9529c8bbdcc392c/scipy/stats/tests/test_continuous_basic.py#L963-L964
