### ISSUE TITLE
DOC: Update toolchain roadmap

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#19815]
It's been a while since https://github.com/scipy/scipy/pull/16589, and the toolchain roadmap has a bunch of things that should be updated. I'd also like to move much of the historical context into separate sections (or better: fold outs, if our docs support that).

* [ ] Remove/hide/rewrite historical cruft
* [ ] Note meson transition & requirement
* [ ] Update relation to `oldest-supported-numpy` (about to be deprecated) and numpy 2.0
* [ ] Update LLVM minimum version
* [ ] Validate current images & compilers
* [ ] Describe use/role of openblas wheel
* [ ] Update current compiler constraints (mostly C++ side)
* [ ] Update fortran compiler constraints (gfortran should IMO match our GCC requirement; flang needs to distinguish llvm-flang)
* [ ] Make Pythran required (c.f. https://github.com/scipy/scipy/issues/18683)
* [ ] Note new Accelerate LAPACK as of MacOS 13.3
* [ ] Update doc dependencies (I doubt we're still compatible with matplotlib 2)
* [ ] Update packaging section
* [ ] Note plans to move windows builds to llvm-flang
* [ ] Note our submodules and relevant constraints
  * For all, but boost especially
* [ ] Note stdlib requirements (relevant for things like `aligned_alloc`, which we already have in use through pocketfft)?
  * We have an effective glibc lower bound based which images in our CI (resp. the ones in conda-forge); glibc <2.17 had a bunch of issues in trig functions, for example
  * Introduce policy for minimal macOS deployment target? (c.f. [this comment](https://github.com/scipy/scipy/pull/19811#issuecomment-1879476807))
  * Windows does not support `aligned_alloc` in a sane manner (see [this comment](https://github.com/scipy/scipy/issues/19726#issuecomment-1869849094) resp. #19761), same for `<complex>` (e.g. we could document the undocumented `_CRT_USE_C_COMPLEX_H`; I have some relevant STL issue links).
  * Might want to write something about usage of various `atomic_*` things, where the ABI is a freaking mess everywhere.

Let me know if there's something else you think should be fixed, or something above you disagree with.

CC @rgommers, we might want to note some of the longer-term improvements you've been pursuing across the stack as well?

**Comment by lucascolley** [comment]
> Note new Accelerate LAPACK as of MacOS 13.3

Good timing gh-19816

**Comment by rgommers** [comment]
These all look like good topics to me, +1 for making this update.

> We have an effective glibc lower bound based which images in our CI (resp. the ones in conda-forge); glibc <2.17 had a bunch of issues in trig functions, for example

Probably not as strict a bound as you think - `libnpymath` fixes all the issues we know of with older `glibc` versions.

> Note our submodules and relevant constraints 

Also note that we plan to move them all under `subprojects` and enable linking to external versions if a distro has the right version packaged already.

> Introduce policy for minimal macOS deployment target?

Just a note that NumPy recently had an issue we fixed for MacPorts, which still supports as far back as macOS 10.6 PPC (yes, I know). Not worth a lot of effort obviously, but also no need to break things unnecessarily. 

We can bump wheel lower bound to 10.13 or 10.15 though, if that is convenient.

**Comment by h-vetinari** [comment]
> Probably not as strict a bound as you think - `libnpymath` fixes all the issues we know of with older `glibc` versions.

I had forgotten about the workarounds there, but the point remains that anything below the lowest glibc version we're testing against is at a high risk of breaking, and we (IMO) shouldn't claim support below that. As of now, the lowest is glibc 2.17 through conda-forge. Actually, speaking of `libnpymath`, we should probably note https://github.com/scipy/scipy/issues/17498.

> Also note that we plan to move them all under `subprojects` and enable linking to external versions if a distro has the right version packaged already.

That sounds awesome! I see now that I had missed #17751.

> We can bump wheel lower bound to 10.13 or 10.15 though, if that is convenient.

Yeah, 10.15 would be convenient for `aligned_alloc` support. 10.14 might work as well. The DL numbers speak a pretty clear language though (it's <<1% for pillow; we could do the [analysis](https://discuss.python.org/t/moving-packaging-and-installers-to-macos-10-13-as-a-minimum/31907/5) for scipy as well of course).

**Comment by h-vetinari** [comment]
> @h-vetinari: CC @rgommers, we might want to note some of the longer-term improvements you've been pursuing across the stack as well?

A few other things that come to mind, WDYT?
* meson support for various BLAS/LAPACK implementations (https://github.com/mesonbuild/meson/pull/10921)
* Stuff around ILP64 (and the rest of #16293)
* getting all the LAPACK implementations to support side-by-side installation of those symbols
* cross-compilation support (#14812)
* #16352
* LTO? #16098
* SIMD things (#16984, #17111), or even runtime dispatch like numpy?
* more platform support? ([pyodide](https://github.com/scipy/scipy/issues/17413) [risc-v](https://github.com/scipy/scipy/issues/19378), loongarch?)
* removing old fortran bits (#18566)
* switching in modern fortran libs (e.g. #18118)

**Comment by h-vetinari** [comment]
> I'd also like to move much of the historical context into separate sections (or better: fold outs, if our docs support that).

@tupui, since you were working on the docs a lot, could you let me know if there's a way to do this, e.g. something like the following:

<details>
<summary>A foldout</summary>

```
Surprise!
```

</details>

The only related mention I found is #18300, but I couldn't tell how this was done. I found a related sphinx [extension](https://sphinx-toolbox.readthedocs.io/en/stable/extensions/collapse.html), any blockers to using that?

**Comment by tupui** [comment]
What about this? Looks like what you are looking for? 
https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/web-components.html#dropdowns

**Comment by h-vetinari** [comment]
> What about this? Looks like what you are looking for?

Yeah, looks great, thanks a lot! I guess I'll wait for your pydata-spinx-theme PR to land (oldest theme docs are 0.11, so I don't know if dropdowns are supported in our currently-used 0.8)

**Comment by rgommers** [comment]
> A few other things that come to mind, WDYT?

I suggest being careful here in keeping the split between the regular roadmap and the toolchain roadmap. The latter is about dependencies and their versions. Some of the things you're suggesting now are "things inside SciPy to work on" and may already be covered in the top-level or detailed roadmap, or they belong there.

http://scipy.github.io/devdocs/dev/roadmap.html#support-for-more-hardware-platforms

> removing old fortran bits

This seems to me to be important enough to become a new top-level item. The bullet below it, "switching in ..." is not a separate target, but part of removing F77 I'd say.

> meson support for various BLAS/LAPACK implementations [...]

Splitting out BLAS and LAPACK from http://scipy.github.io/devdocs/dev/toolchain.html#other-libraries into their own separate section and adding more detail there would be useful I think.

> cross-compilation support [...], gh-16352, LTO

I'd suggest one new section about further build system improvements near the top of the detailed roadmap.

> SIMD things

No concrete plans for this one, not sure if we should add it. If we do, it should be on the detailed roadmap I'd say.

**Comment by ev-br** [comment]
> removing old fortran bits

We have some of this in the detailed roadmap: https://docs.scipy.org/doc/scipy-1.11.4/dev/roadmap-detailed.html#use-of-venerable-fortran-libraries

**Comment by h-vetinari** [comment]
I've made a PR to address the first couple of points here, comments welcome: #20454
