### ISSUE TITLE
META: Streamlined Special Function Development in SciPy SDG Tracking

### ISSUE THREAD

**Issue by steppi** [scipy/scipy#20223]
This issue is intended for tracking milestones for the 2023 NumFocus small development grant for working on `scipy.special` infrastructure.

The original plan for this grant was to work on developing infrastructure for implementing special functions with [Pythran](https://pythran.readthedocs.io/en/latest/), using primitives which abstract over low level details. This plan was been abandoned in favor of efforts to write special functions in CUDA compatible C++ to help improve special function availability on GPU-aware array libraries like CuPy, PyTorch, and Jax, discussed [here](https://github.com/scipy/scipy/issues/19404).

NumFocus has granted a no-cost extension, and the goal is to wrap up these deliverables by end of August this year.

This first block of deliverables is for general special function infrastructure.

- [ ] Infrastructure for special function development in CUDA compatible C++.
- [ ] Series evaluation primitives in CUDA compatible C++.
- [ ] Continued fraction evaluation primitive in ...
- [ ] Kahan Summation primitive.
- [ ] Root finding primitive.
- [ ] Generic Miller's algorithm framework for solving recurrences for argument reduction of special functions. (Stretch goal)
- [ ] Framework for generating rational and polynomial approximations (e.g. Pade approximants, Minimax), for use in special functions.

This second block is for documentation improvements.

Detailed documentation for how to use the infrastructure described above.
- [ ] Document how to write special functions in CUDA compatible C++.
- [ ] Document how to use series evaluators.
- [ ] Document how to use continued fraction evaluators.
- [ ] Document Kahan summation
- [ ] Document Generic Miller's algorithm framework
- [ ] Document framework for generating rational and polynomial approximations.
- [ ] Document best practices for implementing numerically robust functions.
- [ ] Document best practices for testing new special functions.

Finally, a list of issues we hope to close.

- [ ] #3890
- [ ] #8424 
- [ ] #15582
- [ ] #14117
- [ ] #15650 
- [ ] #15151
- [ ] #10795 
- [ ] #7722
- [ ] #14073
- [ ] #5349

cc @tirthasheshpatel @rlucas7

**Comment by j-bowhay** [comment]
Thanks @steppi, I am interested in improving Pade approximants in SciPy, see #20064 and [my recent mailing list post](https://mail.python.org/archives/list/scipy-dev@python.org/thread/3CBCZJCRLUZLHF2ZSV4XWUL2S3XEMOOY/). I was planning on implementing the method described in Trefethen paper and co paper [Robust Pade Approximation via SVD](https://people.maths.ox.ac.uk/trefethen/publication/PDF/2011_144.pdf) (and also used in Chebfun) when I eventually get some free time from university. Is there is there any crossover here?

**Comment by steppi** [comment]
> Thanks @steppi, I am interested in improving Pade approximants in SciPy, see #20064 and [my recent mailing list post](https://mail.python.org/archives/list/scipy-dev@python.org/thread/3CBCZJCRLUZLHF2ZSV4XWUL2S3XEMOOY/). I was planning on implementing the method described in Trefethen paper and co paper [Robust Pade Approximation via SVD](https://people.maths.ox.ac.uk/trefethen/publication/PDF/2011_144.pdf) (which is also used in Chebfun) when I eventually get some free time from university. Is there is there any crossover here?

That's a cool idea and I hope you get time for it soon. I don't think there will be crossover though. For `special` we'd be interested in using arbitrary precision, which is [already in mpmath](https://mpmath.org/doc/current/calculus/approximation.html#pade-approximation-pade) and symbolic computation, which could be built on top of SymPy.

**Comment by ilayn** [comment]
I think we should also consider the testing mechanisms we have. There is no transparency in what is being tested and with what data points.

**Comment by mdhaber** [comment]
It was in the proposal to document best practices for testing special functions. We didn't commit to delivering `mparray` as part of the grant, but that was in mind.

**Comment by steppi** [comment]
> It was in the proposal to document best practices for testing special functions. We didn't commit to delivering `mparray` and a full framework as part of the grant, but that sort of thing was in mind.

I changed it to a stretch goal above to reflect that it wasn't in the proposal, but we still plan to do it.

**Comment by steppi** [comment]
I've created a spreadsheet for every function that I think is in scope for the C++ translations. I was going to create a tracking issue for everything, but have decided to hold off until this one is closed. Just posting this here for anyone interested in seeing it. I plan to keep it up to date as we add things.

https://docs.google.com/spreadsheets/d/1Iw7C9--CCD6z_b3Oq4diba-x_9b303yDcNHBHbznGTQ/edit?usp=sharing

**Comment by fancidev** [comment]
May I ask for more details about the bullet point “root finding primitives”?

The reason I’m asking is that I’m writing a function to find $x$ such that $I_\nu(x)/I_{\nu-1}(x)=\rho$ for given $\nu$ and $\rho$. I’d like to use a root finder for this purpose because I haven’t found other alternatives.

The function is increasing and concave, a “textbook example” for Newton’s method. On the other hand, for extreme inputs the derivative becomes very close to zero, which makes Newton’s method tricky. A robust root finding primitive would be very helpful for this case.

Therefore I’d like to know what you envision for the “root finding primitive” for this meta issue. Also I see there are already many root finding algorithms in SciPy (though for a “higher-level”), so I wonder where would a root finding “primitive” fit.

**Comment by steppi** [comment]
> May I ask for more details about the bullet point “root finding primitives”?

Sure. What I had in mind was basically just to re-implement the solver from [cdlib](https://github.com/scipy/scipy/blob/66ec33370c889e9c9acba320354b624ee258ee22/scipy/special/cdflib.c#L5722) in a modern C++ style and such that it can work in CUDA, so we can add more functions from cdflib to CuPy.

cdflib uses algorithm R from the [Bus and Dekker 1975](https://ir.cwi.nl/pub/20561/20561A.pdf) [1]

1. J. C. P. Bus, T. J. Dekker, Two Efficient Algorithms with Guaranteed Convergence for Finding a Zero of a Function, ACM Trans. Math. Software 1:4 (1975) 330-345, DOI:10.1145/355656.355659

**Comment by duetosymmetry** [comment]
Issue #15151 was just closed as duplicate of #4452. Can #4452 be added to the original list of issues you hope to close, taking the place of #15151?

**Comment by mdhaber** [comment]
Done. I will post on gh-4452 shortly. In short, the definition of `ellippiinc` in terms of `elliprf` and `elliprj` just works.

**Comment by dschmitz89** [comment]
As you will be working on documentation: one point which also complicates contributing to `special` is the maze of wrappers of wrappers as well as the duplication of functions across different backend libraries. Is if feasible to document where each ufunc actually comes from? I was for example surprised to read that `gdtr` actually came from `cephes` while one of its inverse functions, `gdtrib`, came from `cdflib`, so it was not actually inverting the function it was supposed to.

Regarding boost, we are currently unfortunately going down a similar road where the same boost function is wrapped two times, one time for `special` and one time for `stats`. This code duplication needs to be removed. `stats` should simply dispatch to `special` when a function is available. If a function is supposedly a CDF or PPF, let's try it as one and ignore other definitions.
