### ISSUE TITLE
DOC: update roadmap

### ISSUE THREAD

**Issue by lucascolley** [scipy/scipy#22209]
Various ideas for further updates to the roadmap following gh-22101.

---

From me:

RE: roadmap:

- [ ] The support for distributed and GPU arrays section is outdated. We should link to https://github.com/scipy/scipy/issues/18867 and https://github.com/scipy/scipy/issues/18286.

RE: detailed roadmap:
- [ ] "Reliability of CI has not been good recently" seems outdated. Also the discussion of dropping distutils
- [ ] linalg: "Accelerate support is dropped because Apple doesn’t update Accelerate anymore"
- [ ] odr: https://github.com/scipy/scipy/issues/7107
- [ ] sparse: can mention work on ND COO https://github.com/scipy/scipy/issues/21923
- [ ] special: should mention xsf and link to https://github.com/scipy/xsf/issues/1

---

signal stuff from @DietBru:

Two maintenance-related points come to mind:

1. Deprecate [_spectral_helper], [_triage_segments] and [_fft_helper]. 
Currently, [csd] is the only non-legacy function utilizing those internal functions. There already exists a [ShortTimeFFT]-based wrapper, for testing, namely [_csd_wrapper], to ensure that [ShortTimeFFT] provides a superset of functionality. This means that also the legacy functions [stft] and [spectrogram] will be deprecated.

2. Remove [To-Do List Wiki-Page].
It would be nice if the points on the [To-Do List Wiki-Page] could be updated and the still relevant entries could be converted into issues or be merged into this roadmap. 

[_spectral_helper]: https://github.com/scipy/scipy/blob/639bdb83ef66dfa49158edecafffb3eb463c9151/scipy/signal/_spectral_py.py#L1863
[_triage_segments]: https://github.com/scipy/scipy/blob/639bdb83ef66dfa49158edecafffb3eb463c9151/scipy/signal/_spectral_py.py#L2207
[_fft_helper]: https://github.com/scipy/scipy/blob/639bdb83ef66dfa49158edecafffb3eb463c9151/scipy/signal/_spectral_py.py#L2158
[stft]: https://github.com/scipy/scipy/blob/639bdb83ef66dfa49158edecafffb3eb463c9151/scipy/signal/_spectral_py.py#L1248
[spectrogram]: https://github.com/scipy/scipy/blob/639bdb83ef66dfa49158edecafffb3eb463c9151/scipy/signal/_spectral_py.py#L816
[csd]: https://github.com/scipy/scipy/blob/639bdb83ef66dfa49158edecafffb3eb463c9151/scipy/signal/_spectral_py.py#L660
[_csd_wrapper]: https://github.com/scipy/scipy/blob/639bdb83ef66dfa49158edecafffb3eb463c9151/scipy/signal/tests/_scipy_spectral_test_shim.py#L237
[ShortTimeFFT]: https://scipy.github.io/devdocs/reference/generated/scipy.signal.ShortTimeFFT.html
[To-Do List Wiki-Page]: https://github.com/scipy/scipy/wiki/%60scipy.signal%60-to%E2%80%90do-list

---

@andyfaff said

> The default MacOS wheels will use Accelerate for macOS >=14. It's only older OS versions that will use OpenBLAS.

---

Interpolate stuff from @ev-br:

FITPACK replacements
---------------------------------

We need to finish providing functional equivalents of the FITPACK Fortran library. The aim is to reimplement the algorithmic content of the FITPACK monolith in a modular fashion, to allow better user control and extensibility.
To this end, we need

- 1D splines: add the periodic spline fitting to `make_splrep` function.
- 2D splines: provide functional replacements of the `BivariateSpline` family of classes for scattered and gridded data.  

Once we have a feature-complete set of replacements, we can gracefully sunset our use of FITPACK.

Ideas for new features
---------------------------------

- add the ability to construct smoothing splines with variable number of knots to `make_smoothing_spline`. Currently, `make_smoothing_spline` always uses all data points for the knot vector.
- experiment with user-selectable smoothing criteria: add the P-splines penality form to complement the 2nd derivative penality of `make_smoothing_spline` and jumps of the 3rd derivative of `make_splrep`
- investigate ways of vectorizing the spline construction for batches of the independent variable. This class of features have been requested by `scipy.stats` developers
- allow specifying the boundary conditions for spline fitting.
- investigate constrained spline fitting problems which the FITPACK library was providing in Fortran, but were never exposed to the python interfaces
- NURBS support can be added if there is sufficient user interest

Scalability and performance
-----------------------------------------

We need to check performance on large data sets and improve where lacking. This is relevant for both regular grid N-D interpolators and QHull-based scattered N-D interpolators. For the latter ones, we additionally need to investigate if we can improve on the 32-bit integer limitations of the QHull library.

**Comment by j-bowhay** [comment]
I think the interpolate stuff has already been done
