### ISSUE TITLE
a tracking issue for work on univariate b-splines

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#6730]
Following up on gh-3174 which introduced a `BSpline` wrapper, here's a tentative TODO list

Easy-fix tasks:
- [x] Add evaluation of periodic splines. The interface should be consistent with `PPoly` and friends: the "extrapolate" keyword should get the allowed value "periodic" whereby the argument is reduced to the range `(t[k], t[-k])`.  (Done in https://github.com/scipy/scipy/pull/7185)
- [x] it should be possible to construct a BSpline object from a continuous polynomial. This might be tricky in general because of continuity, but at least one should be able to convert a `CubicSpline` object to a BSpline. --- done in https://github.com/scipy/scipy/pull/14554 for `CubicSpline`s
- [x] Add string aliases to the `bc_type` keyword of `make_interp_spline` to match what `CubicSpline` allows. I.e. `bc_type="natural"` should be equivalent to `bc_type=((2, 0), (2, 0))` etc. --- Done in gh-8540
- [x] Rework the tutorial for scipy.interpolate. ATM, the 1D interpolation section prominently recommends `interp1d`. We likely want to tone it down and recommend instead CubicSpline, Akima1DInterpolator, BSpline etc. --- cf gh-16707

Slightly trickier:
- [x] <s>Come up with better names for `make_interp_spline`/`make_lsq_spline` routines. Preferably before the names are pinned by a release :-). </s> the ship has sailed.
- [x] Knot insertion. BSpline class  should grow a method `insert_knot` (or insert_knots). This can either wrap `fitpack.insert` directly, or reuse parts of it (e.g. retain the buffer swapping plumbing from `_fitpack` and reimplement the Fortran routine `fitpack/fpinst.f` in C or Cython).
--- cf https://github.com/scipy/scipy/pull/19777
- [ ] Root-finding. At a minimum, `sproot` should be wrapped into a method of BSpline class. Better still, it should be generalized to allow non-cubic splines. The interface should mirror PPoly.solve and PPoly.roots 
- [x] Constructing periodic splines. Fitpack does it. With full matrices it's straightforward, need to work with banded matrices.--- done in https://github.com/scipy/scipy/pull/13701

Bigger projects:
- [ ] Cardinal splines (splines with equidistant knots). We need representation, evaluation and construction. scipy.signal has some. The task here is to have an interface which is both compatible with regular b-splines and piecewise polynomials and is useful for the signal processing folks.
- [ ] Spline fitting to data. ATM there's only FITPACK, and we want a more controllable alternative. A first exploratory shot could be to implement de Boors's `newknot` routine and see how it behaves in real life.

**Comment by rgommers** [comment]
As commented on the mailing list, `` scipy.signal has some.`` is misleading. The B-spline stuff in ``signal`` should probably just be deprecated.

**Comment by ev-br** [comment]
OK, yes, indeed. Originally I meant also
 https://github.com/scipy/scipy/blob/master/scipy/signal/D_bspline_util.c et al, but now that I look at it, it's something different.

**Comment by rainwoodman** [comment]
Hi, I wonder if there is plan or decision about gcvspl.f ? It implements a different set of smoothing algorithms  (include cross validation) for natural splines. I noticed it was mentioned there will be support to natural splines with the new BSpline curves?

**Comment by ev-br** [comment]
Interpolating natural splines are supported: `make_interp_spline(x, y, bc_type=[(2, 0), (2, 0)])`.

For GCV type smoothing, I'm not aware of any plan or discussion. IMO it'd be very nice to have it as an option. gcvspl.f specifically seems to GPL'ed hence license incompatible however.

**Comment by rainwoodman** [comment]
Thanks --  gcvspl.f is excluded then. natural spline smoothing is not supported by the lsq method. Any plans to add that?

**Comment by ev-br** [comment]
There certainly are plans for more knot selection methods. No ETA though, help wanted and appreciated.

**Comment by rainwoodman** [comment]
Is it worthwhile to contact the author of gcvspl.f for a relicense? If the
plan is to reimplement all of the methods then there is not much point
doing that.

**Comment by ev-br** [comment]
> Is it worthwhile to contact the author of gcvspl.f for a relicense?

Certainly!

> If the plan is to reimplement all of the methods then there is not much point

There is no plan to reimplement all methods. Repeat: there is no plan to reimplement for the sake of reimplementing. The plan is to improve separation of concerns, decouple evaluations from construction (which is \approx monolithic in FITPACK), and allow for more flexibility in constructing approximating splines. Both algorithmically (to my knowledge at least, there is no generally best algorithm, so we might want to offer several) and with a better API (see, e.g., https://github.com/scipy/scipy/issues/2579).

**Comment by rainwoodman** [comment]
Unfortunately, the author of gcvspl died a long time ago according to this.

https://github.com/carandraug/octave-spline-gcvspl/blob/master/COPYING

The octave people have tried and failed to obtain a relicence. So probably
a reimplementation shall be done; I'll look at porting it over native to
the BSpline implementation in scipy.

**Comment by charris** [comment]
Apparently Dutch copyright expires 70 years after the death of the author, so that's out for most of this century.

**Comment by lorentzenchr** [comment]
Another point on the issue wishlist could be a way to return a sparse design matrix from `BSpine.__call__`. If you want to use b-splines in larger linear models, i.e. with many more terms than only splines, it would be very nice to get back the spline basis functions evaluated at the input `x` as a sparse matrix. Currently, I use
```python
x = ...  # my input, i.e. values on which to evaluate b-splines
c = np.eye(n_splines)  # trick to get back whole spline matrix
BSpline(t, c, k)(x)
```
This returns an ndarray (with many zeros).

**Comment by ev-br** [comment]
Makes sense. 
I think it's best implemented as a separate function, either top-level `scipy.interpolate.bspline_matrix` or a BSpline classmethod, `BSpline.design_matrix` or some such. 
Internally, it could use https://github.com/scipy/scipy/blob/master/scipy/interpolate/_bspl.pyx#L161 

Would you be interested in sending a PR @lorentzenchr ?

**Comment by lorentzenchr** [comment]
@ev-br Thanks for the links. It is still not that trivial because usually, `x` is not sorted such that the banded structure is not obvious.

I'd be interested but short on time. If someone else is faster with a PR, I'd be happy to help out, e.g. by reviewing.

**Comment by ev-br** [comment]
I think this issue has run its course (or over-run it, if anything). Out the remaining items, 
- root-finding: I checked `sproot` and it's converting to the power basis (https://github.com/scipy/scipy/blob/main/scipy/interpolate/fitpack/sproot.f and https://github.com/scipy/scipy/blob/main/scipy/interpolate/fitpack/fpcuro.f), so it's hardly much better than the standing workaround of `PPoly.from_spline(spl).roots()`;
- cardinal splines are tracked in https://github.com/scipy/scipy/issues/10180 and the current recommendation is to delegate to ndimage;
- spline fitting is tracked in https://github.com/scipy/scipy/issues/2579
